# Generated by Django 6.0.2 on 2026-02-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='idProducto',
            field=models.ForeignKey(db_column='idProducto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='idTipo',
            field=models.ForeignKey(db_column='idTipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipoproductos'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='envio',
            field=models.BooleanField(default=True),
        ),
    ]
