# Generated by Django 6.0.2 on 2026-02-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproductos',
            options={'verbose_name': 'tipoproducto', 'verbose_name_plural': 'tiposproductos'},
        ),
        migrations.AlterModelTable(
            name='tipoproductos',
            table='tipoproductos',
        ),
    ]
