# Generated by Django 6.0.2 on 2026-02-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tipoproductos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproductos',
            options={'verbose_name': 'tipoproducto', 'verbose_name_plural': 'tiposproducto'},
        ),
        migrations.AlterModelTable(
            name='tipoproductos',
            table='tipoproducto',
        ),
    ]
