# Generated by Django 6.0.2 on 2026-03-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_detalleventa_id_alter_venta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id',
        ),
        migrations.AddField(
            model_name='compra',
            name='idCompra',
            field=models.AutoField(db_column='idCompra', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Producto',
            field=models.ForeignKey(db_column='Producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
    ]
