# Generated by Django 6.0.2 on 2026-04-16 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_detalleventa_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('info', 'Información'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación email',
                'verbose_name_plural': 'notificaciones email',
                'db_table': 'notificacion_email',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
