# Generated by Django 6.0.2 on 2026-03-03 02:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_compra_id_compra_idcompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Administrador',
            field=models.ForeignKey(db_column='idAdministrador', on_delete=django.db.models.deletion.CASCADE, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Producto',
            field=models.ForeignKey(db_column='idProducto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(blank=True, db_column='estado', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(db_column='fechaCompra', default=datetime.datetime.now),
        ),
    ]
