# Generated by Django 6.0.2 on 2026-02-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tipoproductos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unidad_medida',
            table='unidadmedida',
        ),
    ]
