# Generated by Django 6.0.3 on 2026-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_codigo_barras_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_index=True, default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoproductos',
            name='nombre_tipo',
            field=models.CharField(db_column='nombre', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre_unidad',
            field=models.CharField(db_column='nombreUnidad', db_index=True, max_length=100),
        ),
    ]
