# Generated by Django 6.0.3 on 2026-03-16 12:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_compra_options_remove_compra_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(db_column='fecha', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Administrador',
            field=models.ForeignKey(db_column='Administrador_id', on_delete=django.db.models.deletion.CASCADE, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Producto',
            field=models.ForeignKey(db_column='Producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(db_column='Proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='idCompra',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
