# Generated by Django 6.0.2 on 2026-03-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_compra_administrador_alter_compra_producto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'idMarca', 'idTipo')},
        ),
    ]
