# Generated by Django 6.0.2 on 2026-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_unidad_medida_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(db_column='idProducto', primary_key=True, serialize=False),
        ),
    ]
