# Generated by Django 6.0.3 on 2026-03-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_compra_fecha_compra_fechacompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='idAdministrador',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
