# Generated by Django 6.0.2 on 2026-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_producto_id_producto_idproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproductos',
            options={'verbose_name': 'tipo_producto', 'verbose_name_plural': 'tipos_productos'},
        ),
        migrations.RemoveField(
            model_name='tipoproductos',
            name='id',
        ),
        migrations.AddField(
            model_name='tipoproductos',
            name='idTipo',
            field=models.AutoField(db_column='idTipo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoproductos',
            name='descripcion',
            field=models.TextField(db_column='descripcion'),
        ),
        migrations.AlterField(
            model_name='tipoproductos',
            name='nombre_tipo',
            field=models.CharField(db_column='nombre', max_length=100),
        ),
    ]
