# Generated by Django 6.0.2 on 2026-02-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tipoproductos_options_remove_tipoproductos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='id',
        ),
        migrations.AddField(
            model_name='marca',
            name='idMarca',
            field=models.AutoField(db_column='idMarca', primary_key=True, serialize=False),
        ),
    ]
