# Generated by Django 6.0.2 on 2026-02-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_marca_id_marca_idmarca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad_medida',
            name='id',
        ),
        migrations.AddField(
            model_name='unidad_medida',
            name='idUnidad',
            field=models.AutoField(db_column='idUnidad', primary_key=True, serialize=False),
        ),
    ]
