# Generated by Django 6.0.2 on 2026-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_unidad_medida_id_unidad_medida_idunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_medida',
            name='abreviatura',
            field=models.CharField(db_column='abreviatura', max_length=10),
        ),
        migrations.AlterField(
            model_name='unidad_medida',
            name='nombre_unidad',
            field=models.CharField(db_column='nombreUnidad', max_length=100),
        ),
    ]
