# Generated by Django 6.0.3 on 2026-03-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_migrar_admins_a_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Producto',
            field=models.ForeignKey(blank=True, db_column='Producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
