# Generated by Django 6.0.2 on 2026-02-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_unidad_medida_abreviatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipoproductos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id',
        ),
        migrations.AddField(
            model_name='administrador',
            name='idAdministrador',
            field=models.AutoField(db_column='idAdministrador', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idCliente',
            field=models.AutoField(db_column='idCliente', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='idCompra',
            field=models.AutoField(db_column='idCompra', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='idPedido',
            field=models.AutoField(db_column='idPedido', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='idProveedor',
            field=models.AutoField(db_column='idProveedor', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='idReporte',
            field=models.AutoField(db_column='idReporte', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='idVenta',
            field=models.AutoField(db_column='idVenta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Administrador',
            field=models.ForeignKey(db_column='idAdministrador', on_delete=django.db.models.deletion.CASCADE, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_administrador',
            field=models.ForeignKey(db_column='idAdministrador', on_delete=django.db.models.deletion.CASCADE, to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_cliente',
            field=models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
