# Generated by Django 6.0.3 on 2026-03-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol',
        ),
    ]
