# Generated by Django 6.0.3 on 2026-04-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin', 'Administrador')], default='admin', max_length=20, verbose_name='Rol'),
        ),
    ]
